### ISSUE TITLE
HTTP DELETE.vi broken: required input 'timeout (0 = Use Default)' is not wired

### ISSUE THREAD

**Issue by kosist** [JKISoftware/JKI-HTTP-REST-Client#13]
LabVIEW 2017, JKI HTTP REST Client v1.3.2.21.
After installation, HTTP DELETE.vi is broken - control "timeout (0 = Use Default)" is not connected to required input of the HTTP Request.vi subVI. Below is the VI snippet.
![DELETE Method](https://user-images.githubusercontent.com/1911151/59578967-e027a980-90ca-11e9-9ab8-22a2f802055b.png)
Is it possible, please, to rebuild toolkit package to avoid this issue? Now, if control is connected to "timeout (0 = Use Default)" of the HTTP Request.vi manually, everything is fixed.

**Comment by jimkring** [comment]
The fix is now available in VIPM and GitHub releases:
https://www.vipm.io/package/jki_lib_rest_client/
https://github.com/JKISoftware/JKI-HTTP-REST-Client/releases/

**Comment by jimkring** [comment]
Thank you for reporting this @kosist and thank you for making the pull request @francois-normandin
