### ISSUE TITLE
[HTTP Request.vi] wrong timeout passed to LV HTTP request

### ISSUE THREAD

**Issue by carlodri** [JKISoftware/JKI-HTTP-REST-Client#14]
In the REST Client\classes\REST Client\HTTP Request.vi, the default timeout value is passed to the LabVIEW HTTP request instead of the user-specified value because of a wrong condition:

![image](https://user-images.githubusercontent.com/5230366/73557962-83f37900-4452-11ea-8ca7-fcf2e106f67f.png)

The `Equals Zero?` should be a `Not Equals Zero?` condition.

**Comment by jimkring** [comment]
The fix is now available in VIPM and GitHub releases:
https://www.vipm.io/package/jki_lib_rest_client/
https://github.com/JKISoftware/JKI-HTTP-REST-Client/releases/

Thank you for reporting this @carlodri and thank you for making the pull request @francois-normandin

**Comment by carlodri** [comment]
Thanks for fixing this!
